### ISSUE TITLE
Most modifications not working

### ISSUE THREAD

**Issue by romancin** [rux616/karabiner-windows-mode#73] opened 2022-11-15 13:14 UTC
Hi!

I have a problem in a new clean. install trying to enable the modifications in this repo. Basic ones are not working currently, like Ctrl + C or Ctrl + V.

I imported all the shortcuts using the command in the README and Enable all.

I deleted the conditional block from the json file, and they started working:

```
"conditions": [
                  {
                     "bundle_identifiers": [
                        "^org\\.virtualbox\\.app\\.VirtualBoxVM$",
                        "^com\\.parallels\\.desktop\\.console$",
                        "^org\\.vmware\\.fusion$",
                        "^org\\.gnu\\.emacs$",
                        "^com\\.jetbrains",
                        "^com\\.microsoft\\.VSCode$",
                        "^com\\.sublimetext\\.3$",
                        "^net\\.kovidgoyal\\.kitty$",
                        "^com\\.citrix\\.XenAppViewer$",
                        "^com\\.microsoft\\.rdc\\.macos$",
                        "^io\\.alacritty$",
                        "^co\\.zeit\\.hyper$",
                        "^com\\.googlecode\\.iterm2$",
                        "^com\\.apple\\.Terminal$",
                        "^com\\.github\\.wez\\.wezterm$"
                     ],
                     "file_paths": [
                        [
                           "Chrome Remote Desktop\\.app"
                        ]
                     ],
                     "type": "frontmost_application_unless"
                  }
               ],
```

I am using Ventura 13.0.1. ¿Is there any problem with this OS version?

Thank you very much!

**Comment by ouaibe** [comment] 2022-11-28 15:53
I can confirm I had the exact same issue on Ventura, the workaround to remove all the condition blocks from the JSON file and reload complex modifications as such fixed it.

**Comment by rux616** [comment] 2022-12-05 02:37
Hmm, I'm not sure why this would have stopped working. The reference manual for Karabiner shows that `frontmost_application_unless` is still valid for complex conditions ([link](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/frontmost-application/)).

Unfortunately, I no longer have a Mac and so can't do any troubleshooting on this.

**Comment by ldtho** [comment] 2022-12-08 02:14
Confirmed, it only works after I remove the "conditions" blocks

**Comment by rux616** [comment] 2022-12-08 02:25
> Confirmed, it only works after I remove the "conditions" blocks

Are you using Ventura as well?

**Comment by ldtho** [comment] 2022-12-08 02:28
Yes I am 👍

**Comment by GnatGoSplat** [comment] 2022-12-13 20:20
Same problem on Ventura 13.0.1 and Karabiner 14.10.0.  Original Macbook Pro M1.
Removing the condition blocks fixed it, but borks everything I needed conditions for, so I wouldn't say it's really a fix.

**Comment by yuan-canva** [comment] 2022-12-19 10:42
PR submitted here https://github.com/rux616/karabiner-windows-mode/pull/74

**Comment by xmrflipflop** [comment] 2022-12-19 10:43
PR submitted here https://github.com/rux616/karabiner-windows-mode/pull/74

**Comment by rux616** [comment] 2022-12-19 21:13
@romancin @ouaibe @ldtho @GnatGoSplat I believe this should be fixed now thanks to PR #74 submitted by @xmrflipflop. Can you import the new JSON and give it a shot?

**Comment by GnatGoSplat** [comment] 2022-12-19 22:58
@rux616 it seems to be working great for me.  Thanks!

**Comment by rux616** [comment] 2022-12-20 00:14
Excellent, good to here. Thanks again for the PR, @xmrflipflop.

**Closed** 2022-12-20 00:15 UTC
